import PageSchema from "@/components/PageSchema"
import { genPageMetadata } from "app/seo"
import Link from "@/components/Link"

export const metadata = genPageMetadata({
  path: "/privacy",
  title: "Privacy Policy",
  description:
    "How DecimalTools collects, uses, and protects information when you use our free online tools at decimaltools.com.",
})

const PrivacyPolicy = () => {
  return (
    <>
      <PageSchema
        path="/privacy"
        name="Privacy Policy"
        description={String(metadata.description)}
        type="WebPage"
        breadcrumbs={[
          { name: "Home", path: "/" },
          { name: "Privacy", path: "/privacy" },
        ]}
      />
      <div className="min-h-screen px-4 py-12 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-4xl overflow-hidden rounded-lg bg-white shadow-xl">
          <div className="px-6 py-8">
            <h1 className="mb-6 text-center text-3xl font-bold text-gray-900">Privacy Policy</h1>
            <p className="mb-8 text-center text-sm text-gray-600">Last updated: April 12, 2026</p>
            <div className="space-y-6 text-gray-700">
              <p>
                This Privacy Policy describes Our policies and procedures on the collection, use and
                disclosure of Your information when You use the Service and tells You about Your
                privacy rights and how the law protects You.
              </p>
              <p>
                This site provides online calculators and converters. Information handled by a tool
                depends on the feature and your browser; do not enter sensitive information unless
                you are comfortable with that processing.
              </p>
            </div>
            <h2 className="mb-4 mt-12 text-2xl font-semibold text-gray-900">
              Interpretation and Definitions
            </h2>
            <h3 className="mb-3 mt-8 text-xl font-semibold text-gray-900">Interpretation</h3>
            <p className="mb-4 text-gray-700">
              The words of which the initial letter is capitalized have meanings defined under the
              following conditions. The following definitions shall have the same meaning regardless
              of whether they appear in singular or in plural.
            </p>
            <h3 className="mb-3 mt-8 text-xl font-semibold text-gray-900">Definitions</h3>
            <p className="mb-4 text-gray-700">For the purposes of this Privacy Policy:</p>
            <ul className="list-disc space-y-2 pl-6 text-gray-700">
              <li>
                <p>
                  <strong>Cookies</strong> are small files that are placed on Your computer, mobile
                  device or any other device by a website, containing the details of Your browsing
                  history on that website among its many uses.
                </p>
              </li>
              <li>
                <p>
                  <strong>Country</strong> refers to the country or region where the user is located.
                </p>
              </li>
              <li>
                <p>
                  <strong>Device</strong> means any device that can access the Service such as a
                  computer, a cellphone or a digital tablet.
                </p>
              </li>
              <li>
                <p>
                  <strong>Personal Data</strong> is any information that relates to an identified or
                  identifiable individual.
                </p>
              </li>
              <li>
                <p>
                  <strong>Service</strong> refers to the Website.
                </p>
              </li>
              <li>
                <p>
                  <strong>Usage Data</strong> refers to data collected automatically, either
                  generated by the use of the Service or from the Service infrastructure itself (for
                  example, the duration of a page visit).
                </p>
              </li>
              <li>
                <p>
                  <strong>Website</strong> refers to DecimalTools, accessible from{" "}
                  <Link
                    href="https://decimaltools.com/"
                    rel="external nofollow noopener"
                    target="_blank"
                    className="text-primary-500 hover:text-primary-400"
                    aria-label="decimaltools website link"
                  >
                    https://decimaltools.com/
                  </Link>
                </p>
              </li>
              <li>
                <p>
                  <strong>You</strong> means the individual accessing or using the Service, or the
                  company, or other legal entity on behalf of which such individual is accessing or
                  using the Service, as applicable.
                </p>
              </li>
            </ul>
            <h2 className="mb-4 mt-12 text-2xl font-semibold text-gray-900">
              Collecting and Using Your Personal Data
            </h2>
            <h3 className="mb-3 mt-8 text-xl font-semibold text-gray-900">
              Types of Data Collected
            </h3>
            <h4 className="mb-2 mt-6 text-lg font-semibold text-gray-900">Information You Provide</h4>
            <p className="mb-4 text-gray-700">
              The calculators do not require an account. If you contact us by email, we receive the
              address and message you choose to send. Some tools process entered values in your
              browser; server logs and third-party tools may process technical request information.
              We have not verified the production configuration for every optional service, so
              contact us with questions about a specific tool or data request.
            </p>

            <h2 className="mb-4 mt-12 text-2xl font-semibold text-gray-900">
              Third-party Services
            </h2>

            <p className="mb-4 text-gray-700">We use the following third-party services:</p>

            <ul className="list-disc space-y-2 pl-6 text-gray-700">
              <li>
                <p>
                  <strong>Microsoft Clarity (analytics)</strong>
                  <br />
                  1. Purpose: Understand how visitors use the site and improve its pages
                  <br />
                  2. Clarity may use cookies and similar technologies and process interaction,
                  device, and browsing information according to the site's Clarity configuration.
                  Whether text typed into a particular tool is collected depends on configured
                  masking and tracking behavior, which should be confirmed before publication.
                  <br />
                  3. More information:{" "}
                  <Link
                    href="https://privacy.microsoft.com/en-us/privacystatement"
                    rel="external nofollow noopener"
                    target="_blank"
                    className="text-primary-500 hover:text-primary-400"
                    aria-label="Microsoft Privacy Statement"
                  >
                    Microsoft Privacy Statement
                  </Link>
                </p>
              </li>
              <li>
                <p>
                  <strong>Google AdSense</strong>
                  <br />
                  1. Purpose: Display and measure advertisements, including personalized ads where
                  enabled and permitted
                  <br />
                  2. Google and its advertising partners may use cookies or similar technologies
                  to serve, measure, and personalize ads. See Google's information about{" "}
                  <Link href="https://policies.google.com/technologies/ads?hl=en" rel="external nofollow noopener" target="_blank" className="text-primary-500 hover:text-primary-400">advertising technologies</Link>{" "}
                  and{" "}
                  <Link href="https://adssettings.google.com/" rel="external nofollow noopener" target="_blank" className="text-primary-500 hover:text-primary-400">ad personalization settings</Link>.
                  <br />
                  3. More information:{" "}
                  <Link
                    href="https://policies.google.com/privacy?hl=en"
                    rel="external nofollow noopener"
                    target="_blank"
                    className="text-primary-500 hover:text-primary-400"
                    aria-label="Google privacy policy link"
                  >
                    Google Privacy Policy
                  </Link>
                </p>
              </li>
            </ul>

            <h2 className="mb-4 mt-12 text-2xl font-semibold text-gray-900">Cookie Policy</h2>
            <p className="mb-4 text-gray-700">
              Cookies or similar technologies may be used for site functionality, analytics, or
              advertising depending on the services enabled in the deployed configuration:
            </p>
            <ul className="list-disc space-y-2 pl-6 text-gray-700">
              <li>Essential cookies: Required for website functionality</li>
              <li>Analytics technologies: Help the enabled analytics provider understand site use</li>
              <li>Advertising technologies: Support ad delivery, measurement, and personalization</li>
            </ul>
            <p className="mb-4 text-gray-700">
              You can manage cookies in your browser. Google ad personalization can also be managed
              through the Google Ads Settings link above. Availability of controls depends on your
              location and the services enabled on the site.
            </p>

            <h2 className="mb-4 mt-12 text-2xl font-semibold text-gray-900">Contact Us</h2>
            <p className="mb-4 text-gray-700">
              If you have any questions about this Privacy Policy, You can contact us:
            </p>
            <ul className="list-disc space-y-2 pl-6 text-gray-700">
              <li>By email: postmaster@decimaltools.com</li>
              <li>Alternatively: geeks.kai@gmail.com</li>
            </ul>
          </div>
        </div>
      </div>
    </>
  )
}

export default PrivacyPolicy
